<img style="float: left; margin: 30px 15px 15px 15px;" src="https://pngimage.net/wp-content/uploads/2018/06/logo-iteso-png-5.png" width="300" height="500" /> 
    
    
### <font color='navy'> Simulación de procesos financieros. 

**Nombres:** #############.

**Fecha:** XX de octubre del 201X.

**Expediente** : XXX.
**Profesor:** Oscar David Jaramillo Zuluaga.
    
**Link Github**: Link con el enlace del repositorio del creador del proyecto

# Proyecto TEMA-2

<img style="float: right; margin: 0px 0px 15px 15px;" src="https://upload.wikimedia.org/wikipedia/commons/b/b6/Proyecto_en_construccion.jpg" width="300px" height="100px" />


# Proyecto Módulo 2- Guía.
> Se especifican los componentes básicos que deberá tener cada proyecto. El proyecto debe ser un problema que utilice datos reales, ya sea de una empresa física real o de alguna página de internet que proporcione bases de datos confiables. Con la información obtenida, se pretende utilizar todas las herramientas vistas durante el curso para la correcta modelación y simulación del cierto problema con ciertas variables de interés.

___
## 1. Entregable.
Los trabajos deben tener los siguientes componentes básicos.

### 1.1 Título del trabajo.
> Debe describir el trabajo.

### 1.2 Objetivos.
> - Se refieren a los propósitos por los cuales se hace el trabajo.
> - Deben ser **concretos, evaluables y verificables.**
> - Deben ser escritos en infinitivo.
> #### 1.1 Objetivo general.
>  - Fin último de estudio. Se formula atendiendo el propósito global del trabajo. No presenta detalles.
>  - Se orienta a la totalidad del trabajo. Tiene que ver con el título del trabajo.
> #### 1.2 Objetivos específicos
>  - De forma detallada describen cada una de los componentes del trabajo.
>  - En conjunto garantizan la consecución del objetivo general.

Referencia:
- https://es.slideshare.net/rosbur/metodologia-objetivos-generales-y-especficos

### 1.3 Definición del problema.
> Se debe describir en una cuartilla máximo cuál es el escenario de negocio que se va a modelar, identificar cuáles son los supuestos que defines en el negocio y cuáles son los "nodos" o "escenarios" que identificas necesarios simular y porqué. Debes elaborar un diagrama de inicio a fin, identificando los "nodos" o "escenarios" a simular.

### 1.4 Nodos y variables que se decidieron simular y porqué
> En este apartado el objetivo es identificar los problemas que se van a abordar, para examinar la factibilidad y viabilidad de la simulación de los nodos escogidos. Posteriormente se debe de argumentar del porqué de los nodos escogidos.

### 1.5 Definición de hipótesis y supuestos.
>  Para poder modelar un proceso de negocio o cualquiera otro proceso en el área de las ingenierías o ciencias sociales, después de identificar el objeto de estudio, es importante indicar cuales son los supuestos que se dan por verdaderos a lo largo de la ejecución del proceso. Estos supuestos se deben indicar en forma de variables e hipótesis (son diferentes), porque si puedes definir en un valor el supuesto lo llamaremos "supuesto constante" y si no es posible identificarlo con un número entonces será una hipótesis que afectará la construcción de los escenarios posibles del proceso.

### 1.6 Obtención de bases de datos
> El tercer paso del proyecto es indicar de dónde se obtendrán las bases de datos, que indican como se han comportado las variables que identificaste en tu proceso de negocio que vas a simular. En esta investigación debes haber encontrado información propia de la empresa, organización o institución que vas a simular y otra parte de la información debe provenir de investigación que realices en fuentes de información públicas o privadas como las que tiene SECOBI, ahí normalmente y dependiendo del problema elegido, se investigan variables económicas, como tasas de interés, inflación, tipo de cambio, etc., de varios años, por poner un ejemplo.

### 1.7 Visualización de resultados de simulación.
> Se deben simular al menos 4  "nodos" o "escenarios" en tu problema. Para la segunda entrega debes haber elaborado un programa que simule dos de ellos, los primeros dos de tu diagrama.
> Para la entrega final deben de tener los 4 nodos con todas sus simulaciones.

### 1.6 Conclusiones.
> Mucho cuidado, las conclusiones no son cualquier cosa. Se debe concluir respecto a los objetivos planteados de acuerdo a los resultados obtenidos.

### 1.7 Referencias.
> Citar (en formato APA) la bibliografía utilizada.

In [26]:
import pandas as pd
from CDIN import CDIN as eda
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np

In [8]:
data = pd.read_csv('previous_app.csv')
#data.info

In [9]:
data.columns

Index(['SK_ID_PREV', 'SK_ID_CURR', 'NAME_CONTRACT_TYPE', 'AMT_ANNUITY',
       'AMT_APPLICATION', 'AMT_CREDIT', 'AMT_DOWN_PAYMENT', 'AMT_GOODS_PRICE',
       'WEEKDAY_APPR_PROCESS_START', 'HOUR_APPR_PROCESS_START',
       'FLAG_LAST_APPL_PER_CONTRACT', 'NFLAG_LAST_APPL_IN_DAY',
       'RATE_DOWN_PAYMENT', 'RATE_INTEREST_PRIMARY',
       'RATE_INTEREST_PRIVILEGED', 'NAME_CASH_LOAN_PURPOSE',
       'NAME_CONTRACT_STATUS', 'DAYS_DECISION', 'NAME_PAYMENT_TYPE',
       'CODE_REJECT_REASON', 'NAME_TYPE_SUITE', 'NAME_CLIENT_TYPE',
       'NAME_GOODS_CATEGORY', 'NAME_PORTFOLIO', 'NAME_PRODUCT_TYPE',
       'CHANNEL_TYPE', 'SELLERPLACE_AREA', 'NAME_SELLER_INDUSTRY',
       'CNT_PAYMENT', 'NAME_YIELD_GROUP', 'PRODUCT_COMBINATION',
       'DAYS_FIRST_DRAWING', 'DAYS_FIRST_DUE', 'DAYS_LAST_DUE_1ST_VERSION',
       'DAYS_LAST_DUE', 'DAYS_TERMINATION', 'NFLAG_INSURED_ON_APPROVAL'],
      dtype='object')

In [14]:
eda.dqr(data)

,Nombre,data_types,missing_values,present_values,unique_values,min,max
SK_ID_PREV,SK_ID_PREV,int64,0,1670214,1670214,1000001,2845382
SK_ID_CURR,SK_ID_CURR,int64,0,1670214,338857,100001,456255
NAME_CONTRACT_TYPE,NAME_CONTRACT_TYPE,object,0,1670214,4,Cash loans,XNA
AMT_ANNUITY,AMT_ANNUITY,float64,372235,1297979,357959,0,418058
AMT_APPLICATION,AMT_APPLICATION,float64,0,1670214,93885,0,6.90516e+06
AMT_CREDIT,AMT_CREDIT,float64,1,1670213,86803,0,6.90516e+06
AMT_DOWN_PAYMENT,AMT_DOWN_PAYMENT,float64,895844,774370,29278,-0.9,3.06004e+06
AMT_GOODS_PRICE,AMT_GOODS_PRICE,float64,385515,1284699,93885,0,6.90516e+06
WEEKDAY_APPR_PROCESS_START,WEEKDAY_APPR_PROCESS_START,object,0,1670214,7,FRIDAY,WEDNESDAY
HOUR_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,int64,0,1670214,24,0,23
FLAG_LAST_APPL_PER_CONTRACT,FLAG_LAST_APPL_PER_CONTRACT,object,0,1670214,2,N,Y
NFLAG_LAST_APPL_IN_DAY,NFLAG_LAST_APPL_IN_DAY,int64,0,1670214,2,0,1
RATE_DOWN_PAYMENT,RATE_DOWN_PAYMENT,float64,895844,774370,207033,-1.49788e-05,1
RATE_INTEREST_PRIMARY,RATE_INTEREST_PRIMARY,float64,1664263,5951,148,0.0347813,1
RATE_INTEREST_PRIVILEGED,RATE_INTEREST_PRIVILEGED,float64,1664263,5951,25,0.37315,1
NAME_CASH_LOAN_PURPOSE,NAME_CASH_LOAN_PURPOSE,object,0,1670214,25,Building a house or an annex,XNA
NAME_CONTRACT_STATUS,NAME_CONTRACT_STATUS,object,0,1670214,4,Approved,Unused offer
DAYS_DECISION,DAYS_DECISION,int64,0,1670214,2922,-2922,-1
NAME_PAYMENT_TYPE,NAME_PAYMENT_TYPE,object,0,1670214,4,Cash through the bank,XNA
CODE_REJECT_REASON,CODE_REJECT_REASON,object,0,1670214,9,CLIENT,XNA
NAME_TYPE_SUITE,NAME_TYPE_SUITE,object,820405,849809,7,NaN,NaN
NAME_CLIENT_TYPE,NAME_CLIENT_TYPE,object,0,1670214,4,New,XNA
NAME_GOODS_CATEGORY,NAME_GOODS_CATEGORY,object,0,1670214,28,Additional Service,XNA
NAME_PORTFOLIO,NAME_PORTFOLIO,object,0,1670214,5,Cards,XNA
NAME_PRODUCT_TYPE,NAME_PRODUCT_TYPE,object,0,1670214,3,XNA,x-sell
CHANNEL_TYPE,CHANNEL_TYPE,object,0,1670214,8,AP+ (Cash loan),Stone
SELLERPLACE_AREA,SELLERPLACE_AREA,int64,0,1670214,2097,-1,4000000
NAME_SELLER_INDUSTRY,NAME_SELLER_INDUSTRY,object,0,1670214,11,Auto technology,XNA
CNT_PAYMENT,CNT_PAYMENT,float64,372230,1297984,49,0,84
NAME_YIELD_GROUP,NAME_YIELD_GROUP,object,0,1670214,5,XNA,middle
PRODUCT_COMBINATION,PRODUCT_COMBINATION,object,346,1669868,17,NaN,NaN
DAYS_FIRST_DRAWING,DAYS_FIRST_DRAWING,float64,673065,997149,2838,-2922,365243
DAYS_FIRST_DUE,DAYS_FIRST_DUE,float64,673065,997149,2892,-2892,365243
DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE_1ST_VERSION,float64,673065,997149,4605,-2801,365243
DAYS_LAST_DUE,DAYS_LAST_DUE,float64,673065,997149,2873,-2889,365243
DAYS_TERMINATION,DAYS_TERMINATION,float64,673065,997149,2830,-2874,365243
NFLAG_INSURED_ON_APPROVAL,NFLAG_INSURED_ON_APPROVAL,float64,673065,997149,2,0,1

#### Variables potenciales:
 1. Monto solicitado
 2. Monto aprovado
 3. NAME_SELLER_INDUSTRY
 4. NAME_PORTFOLIO
 5. NAME_CONTRACT_STATUS
 6. WEEKDAY_APPR_PROCESS_START

### Nodos:

1. Dado un monto solicitado cual es la probabilidad de que el crédito sea aprovado por la misma cantidad.
2. ¿Cual Sector tiene mayor probalidad de conseguir un crédito?
3. ¿Cuál es la probabilidad de que se solicite un crédito Revolvente?
4. ¿Cúal es el valor esperado del monto solicitado por parte de empresas del sector Turismo?
5. ¿Cuál es la probabilidad de que el producto solicitado sea una tarjeta de crédito?
6. ¿Cuál es la cantidad promedio de créditos solicitados los viernes?
7. ¿Cuál es el mayor motivo de rechazo de crédito en el sector de consumo electrónico?

In [27]:
def plot_histogram_discrete(distribucion:'señal de varibles aleatorias de un distribución DISCRETA dada',
                            label:'label del legend a aparecer en el gráfica',
                            densidad:'por defecto regresa el histograma en densidad'=True):
    # len(set(distribucion)) cuenta la cantidad de elementos distintos de la variable 'distribucion'
    plt.figure(figsize=[10,4])
    y, x = np.histogram(distribucion, bins=len(set(distribucion)), density=densidad) 
    plt.bar(x[1:], y, label=label)
    plt.legend()
    plt.show()

In [20]:
data['NAME_SELLER_INDUSTRY'].unique()

array(['Connectivity', 'XNA', 'Consumer electronics', 'Industry',
       'Clothing', 'Furniture', 'Construction', 'Jewelry',
       'Auto technology', 'MLM partners', 'Tourism'], dtype=object)

In [22]:
data['NAME_CONTRACT_TYPE'].unique()

array(['Consumer loans', 'Cash loans', 'Revolving loans', 'XNA'],
      dtype=object)

In [23]:
data['CODE_REJECT_REASON'].unique()

array(['XAP', 'HC', 'LIMIT', 'CLIENT', 'SCOFR', 'SCO', 'XNA', 'VERIF',
       'SYSTEM'], dtype=object)

In [41]:
data['HOUR_APPR_PROCESS_START'].unique()

array([15, 11,  7,  9,  8, 10, 12, 13, 14, 16,  6,  4,  5, 19, 17, 18, 20,
       22, 21,  3,  1,  2, 23,  0], dtype=int64)

___
## 2. Especificaciones adicionales.
En el grupo deben haber mínimo dos integrantes y máximo tres integrantes. Para propósitos logísticos nada más, por favor enumérense como *integrante 1*, *integrante 2* e *integrante 3*.

### 2.1 Notebook de jupyter. 
> Los anteriores numerales los deben desarrollar todos en un notebook de jupyter y llamarlo de la siguiente manera `ProyectoModulo1_ApellidoN1_ApellidoN2_ApellidoN3`, donde `ApellidoNi` hace referencia al apellido materno y la inicial del primer nombre del integrante `i`.

### 2.2 Proyecto en `GitHub`.
> El integrante 1 deberá crear un proyecto en `GitHub` llamado **proyecto_modulo1**, donde tendrán todos los archivos relacionados con el proyecto. Los demás integrantes deben hacer un *fork* del proyecto, seguir el proyecto principal con `GitKraken` y hacer al menos dos contribuciones con *pull request* (como se hizo en la tarea). En el proyecto, deben incluir el repositorio remoto del integrante 1.

### 2.3 Presentación.
> Recuerden que la nota del proyecto es mitad el trabajo, y mitad la presentación. Deben hacer una presentación ya sea en power point o utlizando un notebook de python para presentar el trabajo durante un horario de clase que se será posteriomente definido. La presentación, además de llevar todos los componentes básicos descritos en el entregable, debe llevar una tabla de contenido.
> - Presentación: 10 minutos.
> - Seguir estas recomendaciones: https://es.slideshare.net/MeireComputacion/power-point-pautas-para-una-buen-trabajo

<script>
  $(document).ready(function(){
    $('div.prompt').hide();
    $('div.back-to-top').hide();
    $('nav#menubar').hide();
    $('.breadcrumb').hide();
    $('.hidden-print').hide();
  });
</script>

<footer id="attribution" style="float:right; color:#808080; background:#fff;">
Created with Jupyter by Esteban Jiménez Rodríguez.
</footer>